import { Inter } from "next/font/google";
import "./globals.css";
import HeaderTop from "@/components/TopHeader";
import TopHeader from "@/components/TopHeader";
import MainHeader from "@/components/MainHeader";
import Navbar from "@/components/Navbar";
import MobNavbar from "@/components/MobNavbar";

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TopHeader />
        <MainHeader />
        <Navbar />
        <MobNavbar />
        {children}
      </body>
    </html>
  );
}
